[build]
  command = "node setup.mjs"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["shared/**"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"
